mutation($input: UserInput!){
  insert_users(name: $name, age: $age, id: $id, gender: $gender, address: $address, occupation: $occupation)
    name
    age
    id
    gender
    address
    occupation

    # returning {
    #   id
    #   name
    #   age
    #   gender
    #   address
    #   occupation
    # }
}

