mutation MyMutation {
  insert_posts(
    objects: {
      id: 11
      name: John
      age: 19
      gender: male
      address: NewYork
      occupation: press
    }
  )
  returning {
    name
    age
    id
    gender
    address
    occupation
  }
}

